import Head from "next/head";
import React from "react";
import Home from "../components/Courses/Home/Home";
import Overview from "../components/Courses/Overview/Overview";
import Footer from "../components/Home/Footer/Footer";
import Header from "../components/Home/Header/Header";
import Faq from "../components/Programme/FAQ/Faq";
import Leadership from "../components/Programme/Leadership/Leadership";
import AdditionalFooter from "../components/Home/Footer/AdditionalFooter";
import Roadmap from "../components/Home/Roadmap/Roadmap";
import Offerings from "../components/Courses/Offerings/Offerings";
import Curriculum from "../components/Curriculum/Curriculum";

const courses = () => {
	return (
		<div>
			<Head>
				<title>Doosra College - Programs</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='bg-white'>
				<Header />
			</div>
			<div>
				<Home />
				<Overview />
				<Curriculum />
				<Offerings />
				<Roadmap />
				<Leadership />
				<Faq />
				<AdditionalFooter />
				<Footer />
			</div>
		</div>
	);
};

export default courses;
