import About from "../components/Home/About/About";
import Company from "../components/Home/Company/Company";
import AdditionalFooter from "../components/Home/Footer/AdditionalFooter";
import Footer from "../components/Home/Footer/Footer";
import Header from "../components/Home/Header/Header";
import Homee from "../components/Home/Homee/Homee";
import Feedback from "../components/Home/Feedback/Feedback.js";
import Programs from "../components/Home/Programs/Programs.js";
import Roadmap from "../components/Home/Roadmap/Roadmap";
import Head from "next/head";
import Loader from "../components/Home/Loader/Loader";
import { useEffect, useState } from "react";

export default function Home() {
	const [isLoading, setLoading] = useState(true);

	useEffect(() => {
		setTimeout(() => {
			setLoading(false);
		}, 1200);
	});

	return (
		<div>
			<Head>
				<title>Doosra College - Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{isLoading === true ? (
				<Loader />
			) : (
				<div className=''>
					<Header />
					<Homee />
					<Programs />

					{/* Error on large screens - FEEDBACK */}
					<Feedback color={"bg-gradient-to-b from-[#ECF0FC] to-[#fff]"} />
					<Roadmap />
					<About />
					<Company />
					<AdditionalFooter />
					<Footer />
				</div>
			)}
		</div>
	);
}
