import React from "react";
import Head from "next/head";
import Header from "../components/Home/Header/Header";
import Footer from "../components/Home/Footer/Footer";
import Feedback from "../components/Home/Feedback/Feedback";
import Internship from "../components/Internship/Internship";
import Jobs from "../components/Internship/Jobs";

const internship = () => {
	return (
		<div>
			<Head>
				<title>Doosra College | Internship&apos;s</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='bg-white'>
				<Header />
			</div>
			<div>
				<Internship />
				<Jobs />
				<Feedback
					color={" bg-gradient-to-t from-[#7F393F] via-[#432939] to-[#041933]"}
				/>
				<Footer />
			</div>
		</div>
	);
};

export default internship;
